### PR TITLE
add Positive type

### PR DESCRIPTION
**Pull request by samuelcolvin**

### CODE REVIEW

**Comment by adriangb** [comment]
I'm +1 on this, but I'm thinking these should be type aliases to reduce verbosity:

```python
SupportsGreaterThanType = TypeVar("SupportsGreaterThanType", bound=SupportsGreaterThan)

Positive = Annotated[T, Ge(0)]

foo: List[Positive[int]]
```

**Review by adriangb — APPROVED** [review]

**Comment by samuelcolvin** [comment]
Is there any way we can allow them to be used for both? I can't think of a way immediately.

**Comment by samuelcolvin** [comment]
Edit: I guess we just say you can. And the libraries, or a utility function takes care of recognising both forms.

I'm that case, maybe all our types should be aliases - e.g. so you can do `Gt[int, 42]`.

**Comment by adriangb** [comment]
> I'm that case, maybe all our types should be aliases - e.g. so you can do Gt[int, 42]

How does this work in practice? I have never gotten it to work, especially with nesting

**Comment by Zac-HD** [comment]
My main concern with a `Positive` type is that floats have an explicit sign bit, so `+0.0` is in fact positive according to the obvious representation 😬

**Pull request closed without merging**
