### PR TITLE
Document everything for users and implementors

### LINKED ISSUE #9: I think we should remove `Regex`
I tried writing up `Regex` docs that would describe how people actually want to use them, and...

> `Regex(regex_pattern=p, regex_flags=x)` implies that the string should contain a
> match for `p` with flags `x`, at any position in the string. If you want the
> full string to match, or the match to be at the start or end of the string,
> you can use boundary markers like `^...$`.
> 
> `Regex()` can be used with unicode strings or byte strings; if either are allowed
> we suggest using one `Regex()` item for each type, and therefore ignoring `Regex()`
> items with the wrong string type.
> 
> We do not specify the pattern syntax: libraries may choose to interpret it as
> the Python stdlib `re` module, `regex` package, ECMAscript syntax, etc.,
> and we encourage them to clearly document their chosen interpretation.
> The meaning of the `regex_flags` argument is also implementation-defined.

I think this is sufficiently-implementation-defined that we should just, well, make downstream implementations define their own Regex metadata with more precise semantics.  Either that, or we explicitly separate `PythonRegex(pattern: str|bytes, flags: int)` from `JSONschemaRegex(pattern: str)` and make people choose one.

### PR DESCRIPTION
**Pull request by Zac-HD**
Also closes #9.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
👍 will review next week.

**Comment by Zac-HD** [comment]
Thanks for the review!  Will implement later in the week, or weekend at latest 👍

**Comment by Zac-HD** [comment]
@adriangb @samuelcolvin done 😁

**Review by samuelcolvin — APPROVED** [review]
LGTM

**Pull request merged**
